export const SKILLS = [
  "Python",
  "C/C++",
  "MATLAB",
  "SQL",
  "Machine Learning",
  "Embedded Systems",
  "CAD",
  "PCB Design",
  "Control Systems",
  "Web Dev",
  "Data",
  "Robotics",
  "Prototyping",
  "UI/UX",
  "Testing",
];


export const SKILL_ALIASES: Record<string, string[]> = {
  CAD: ["CAD", "Design", "Aero", "Structures", "Materials", "Mechanical Design"],
  "Embedded Systems": ["Embedded Systems", "embedded", "Robotics", "PCB Design", "Control Systems", "IoT"],
  "Machine Learning": ["Machine Learning", "machine learning", "ML", "Python", "Data", "AI"],
  SQL: ["SQL", "Data", "Data Analysis", "Analytics"],
  "Web Dev": ["Web Dev", "Web Development", "web dev", "Frontend", "Backend", "Full Stack", "Web", "UI/UX"],
  Robotics: ["Robotics", "robotics", "Embedded Systems", "Control Systems"],
  Prototyping: ["Prototyping", "prototype", "Testing", "Research", "rapid prototyping"],
  Data: ["Data", "Data Analysis", "Data science", "analytics", "Analytics", "Power BI", "SQL", "Python"],
  Testing: ["Testing", "test", "Prototyping", "QA"],
  "PCB Design": ["PCB Design", "PCB", "Embedded Systems", "electronics"],
  "Control Systems": ["Control Systems", "controls", "Robotics", "Embedded Systems"],
  Python: ["Python", "Machine Learning", "Data", "Data Analysis"],
  "UI/UX": ["UI/UX", "UX", "UI", "UX/UI", "product design", "Product Design"],
};


export const TYPES = ["CPSC", "ENG"];


export const ENGINEERING_MAJORS = [
  "Biomedical Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Software Engineering",
  "Computer Engineering",
  "Civil Engineering",
  "Chemical Engineering",
];


export const SCIENCE_MAJORS = ["Computer Science"];


export const YEARS = ["1st year", "2nd year", "3rd year", "4th year", "5th year", "Graduate", "Other"];


export const OPPORTUNITIES = [
  
  {
    id: "soar",
    title: "SOAR",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Build rockets and aerospace systems in a milestone-driven team with strong technical mentorship.",
    link: "https://www.soar-rockets.ca/",
  },
  {
    id: "baja",
    title: "Baja",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Design and race an off-road vehicle while learning iterative engineering and hands-on fabrication.",
    link: "https://ucalgbaja.ca/",
  },
  {
    id: "bmerit",
    title: "BMERIT",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Work on biomedical engineering projects that blend prototyping, testing, and real-world impact.",
    link: "https://bmerit.vercel.app/",
  },
  {
    id: "calgarytospace",
    title: "CalgaryToSpace",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Get involved in space-focused builds and research with strong systems integration experience.",
    link: "https://www.calgarytospace.ca/",
  },
  {
    id: "calgary_racing",
    title: "Calgary Racing",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Join a competitive motorsport team with clear subteams, deadlines, and engineering workflow.",
    link: "https://ucalgaryracing.ca/",
  },
  {
    id: "gnctr_toboggan",
    title: "GNCTR (Toboggan)",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Concrete toboggan design and competition with real testing, timelines, and deliverables.",
    link: "https://gnctruofc.wordpress.com/",
  },
  {
    id: "space_rover_team",
    title: "Space Rover Team",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Build robotics systems end-to-end: electronics, autonomy, controls, and field testing.",
    link: "https://ucalgaryrover.weebly.com/",
  },
  {
    id: "suav",
    title: "Unmanned Aerial Vehicles (SUAV)",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Work on UAV autonomy, sensors, controls, and the discipline of flight testing.",
    link: "https://calgaryuav.com/",
  },
  {
    id: "team_zeus",
    title: "Team Zeus",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Electric motorcycle racing with battery systems, embedded work, and a strong testing culture.",
    link: "https://www.teamzeus.ca/",
  },
  {
    id: "solar_car_team",
    title: "Solar Car Team",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Long-horizon build that teaches power systems, embedded telemetry, and engineering stamina.",
    link: "https://calgarysolarcar.ca/",
  },
  {
    id: "waybionic",
    title: "WayBionic",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Assistive and bionics work combining design, prototyping, and interdisciplinary engineering.",
    link: "https://www.waybionic.com/",
  },


  {
    id: "project90",
    title: "Project90",
    type: "ENG",
    tags: ["Teamwork","Communication","Planning","Documentation","Problem Solving","Git","Testing","Python","C/C++","Embedded","SQL","Data Analysis","PCB Design","CAD","Leadership"],
    effort: "6hr-10hr",
    deadline: "Year-Round",
    why: "Engineering community + projects that build leadership, consistency, and real execution habits.",
    link: "https://project90.ca/",
  },
  {
    id: "schulich_ignite",
    title: "Schulich Ignite",
    type: "ENG",
    tags: ["Programming Mentorship","Workshops","Project Building","Teamwork"],
    effort: "1hr-3hr",
    deadline: "Fall and Winter Semesters",
    why: "Grow fast through workshops and mentorship while building confidence in technical foundations.",
    link: "https://schulichignite.com/",
  },
  {
    id: "ucalgary_design_league",
    title: "uCalgary Design League",
    type: "ENG",
    tags: ["CAD","Design Thinking","Prototyping","Designathons"],
    effort: "1hr-4hr",
    deadline: "Year-Round",
    why: "Designathons and hands-on challenges that sharpen CAD, prototyping, and design thinking.",
    link: "https://ucdesignleague.square.site/",
  },
  {
    id: "wise",
    title: "Women in Science and Engineering (WISE)",
    type: "ENG",
    tags: ["Mentorship","Professional Development","STEM Community"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Mentorship and professional development events in a supportive STEM community.",
    link: "https://www.uofcwise.com/",
  },
  {
    id: "ieee_ucalgary",
    title: "IEEE UCalgary Student Branch",
    type: "ENG",
    tags: ["Tech Talks","Networking","Embedded/IoT","Workshops"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Technical talks and workshops that connect you with industry and practical engineering skills.",
    link: "https://ieee-ucalgary.ca/",
  },
  {
    id: "revolt_ev",
    title: "ReVOLT EV",
    type: "ENG",
    tags: ["EV Projects","Embedded/Software","Teamwork","Git"],
    effort: "2hr-6hr",
    deadline: "Year-Round",
    why: "EV-focused projects that blend teamwork with embedded and software development.",
    link: "https://schulich.ucalgary.ca/current-students/undergraduate/student-life/clubs-teams",
  },
  {
    id: "mind_mechatronics_innovation_design",
    title: "MIND (Mechatronics Innovation Design)",
    type: "ENG",
    tags: ["Robotics","Embedded Systems","Prototyping","Teamwork"],
    effort: "2hr-6hr",
    deadline: "Year-Round",
    why: "Mechatronics and robotics builds where you learn by prototyping and iterating with a team.",
    link: "https://www.minducalgary.com/",
  },
  {
    id: "gobabygo_ucalgary",
    title: "GoBabyGo UCalgary",
    type: "ENG",
    tags: ["Assistive Tech","Embedded/Software","Hardware Integration"],
    effort: "1hr-4hr",
    deadline: "Year-Round",
    why: "Assistive technology projects with tangible impact and strong hands-on integration work.",
    link: "https://schulich.ucalgary.ca/current-students/undergraduate/student-life/clubs-teams",
  },
  {
    id: "scrp",
    title: "Schulich Community Robotics Program (SCRP)",
    type: "ENG",
    tags: ["Robotics Outreach","Mentoring","Programming Basics"],
    effort: "1hr-4hr",
    deadline: "Year-Round",
    why: "Teach robotics and programming fundamentals while building mentoring and leadership skills.",
    link: "https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs",
  },
  {
    id: "ucalgary_robotics_club",
    title: "University of Calgary Robotics Club",
    type: "ENG",
    tags: ["Robotics","Programming","Building","Teamwork"],
    effort: "2hr-6hr",
    deadline: "Year-Round",
    why: "A hands-on robotics community for building, learning, and collaborating on projects.",
    link: "https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs",
  },
  {
    id: "minds_in_motion",
    title: "Minds in Motion",
    type: "ENG",
    tags: ["Robotics Mentoring","STEM Outreach","Leadership"],
    effort: "1hr-4hr",
    deadline: "Year-Round",
    why: "Lead youth robotics programming and build confidence as a mentor and facilitator.",
    link: "https://www.ucalgary.ca/active-living/programs/youth-programs/robotics-community-programs",
  },

  
  {
    id: "csus",
    title: "Computer Science Undergraduate Society",
    type: "CPSC",
    tags: ["Networking","Hackathon Participation","Teamwork","Software Project Collaboration","Career Preparation"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "A central hub for CS events, community, and getting plugged into opportunities fast.",
    link: "https://csus.club/",
  },
  {
    id: "competitive_programming_club",
    title: "Competitive Programming Club",
    type: "CPSC",
    tags: ["Algorithms","Data Structures","Problem Solving","Python","C++","Interview Prep"],
    effort: "1hr-3hr",
    deadline: "Fall and Winter Semesters",
    why: "Sharpen algorithms and problem solving with consistent practice and interview-style challenges.",
    link: "https://cpc.cpsc.ucalgary.ca/",
  },
  {
    id: "dsmlc",
    title: "Data Science and Machine Learning Club",
    type: "CPSC",
    tags: ["Python","Machine Learning","SQL","Data Analysis","Power BI","AI Concepts"],
    effort: "2hr-4hr",
    deadline: "Year-Round",
    why: "Build ML and data skills through projects, workshops, and a strong learning community.",
    link: "https://www.dsmlcucalgary.ca/",
  },
  {
    id: "aic",
    title: "Artificial Intelligence Club (AIC)",
    type: "CPSC",
    tags: ["Machine Learning","Neural Networks","Python","AI Research","Project Development"],
    effort: "2hr-5hr",
    deadline: "Fall and Winter Semesters",
    why: "Explore AI through research-style learning and projects with people who take it seriously.",
    link: "https://www.vision-research.ca/aic",
  },
  {
    id: "information_security_club",
    title: "Information Security Club",
    type: "CPSC",
    tags: ["Cybersecurity","Ethical Hacking","Linux","Networking","Security Tools"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Learn security fundamentals through practical exploration, tooling, and community practice.",
    link: "https://www.linkedin.com/company/cybersec-ucalgary/",
  },
  {
    id: "gdc",
    title: "Game Design Club (GDC)",
    type: "CPSC",
    tags: ["Game Development","Unity","C#","Teamwork","Software Design"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Make games with a team while practicing clean software design and creative problem solving.",
    link: "https://uofcgamedesignclub.itch.io/",
  },
  {
    id: "tech_start_ucalgary",
    title: "Tech Start UCalgary",
    type: "CPSC",
    tags: ["Software Dev","Product Building","Teamwork","Git","Agile"],
    effort: "2hr-6hr",
    deadline: "Year-Round",
    why: "Ship real products in cross-functional teams and learn practical dev workflows.",
    link: "https://techstartucalgary.com/",
  },
  {
    id: "dsc_ucalgary",
    title: "Developer Student Club (DSC) UCalgary",
    type: "CPSC",
    tags: ["App Dev","Web Dev","Cloud","Workshops","Networking"],
    effort: "1hr-4hr",
    deadline: "Year-Round",
    why: "Hands-on workshops and community for building apps, web projects, and cloud skills.",
    link: "https://dsc-uofc-website.herokuapp.com/",
  },
  {
    id: "wics",
    title: "WiCS (Women in Computer Science)",
    type: "CPSC",
    tags: ["Networking","Mentorship","Career Talks","Community"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Supportive CS community with mentorship and career events that actually help.",
    link: "https://www.instagram.com/wics.uofc/",
  },
  {
    id: "wicys",
    title: "WiCyS @ UCalgary",
    type: "CPSC",
    tags: ["Cybersecurity","Networking","Career Development","Workshops"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Cybersecurity community focused on skills, confidence, and career development.",
    link: "https://www.instagram.com/wicys.uofc/",
  },
  {
    id: "cybersec_ucalgary",
    title: "CYBERSEC (UCalgary CyberSecurity Club)",
    type: "CPSC",
    tags: ["Cybersecurity","CTFs","Networking","Security Tools"],
    effort: "1hr-4hr",
    deadline: "Year-Round",
    why: "CTFs and security practice for people who want hands-on learning and consistency.",
    link: "https://cybersec-ucalgary.club/",
  },
  {
    id: "uofc_fintech",
    title: "UofC FinTech",
    type: "CPSC",
    tags: ["Fintech Projects","Data Analysis","Python","Networking"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Fintech projects and events that connect software, data, and real industry context.",
    link: "https://suuofc.campuslabs.ca/engage/organization/fintechcalgary",
  },
  {
    id: "ucalgary_blockchain_society",
    title: "UCalgary Blockchain Society",
    type: "CPSC",
    tags: ["Blockchain Fundamentals","Smart Contracts","Dev Workshops","Networking"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Learn blockchain foundations and dev concepts through workshops and community builds.",
    link: "https://suuofc.campuslabs.ca/engage/organization/ucalgary-blockchain-society",
  },
  {
    id: "uxdc",
    title: "User Experience Design Club (UXDC)",
    type: "CPSC",
    tags: ["UX/UI","Product Design","Prototyping","User Research"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Practice UX research and prototyping with people who care about real product thinking.",
    link: "https://linktr.ee/uxdc.uofc",
  },
  {
    id: "stem_fellowship",
    title: "STEM Fellowship UCalgary Branch",
    type: "CPSC",
    tags: ["Workshops","Computational Thinking","Data/AI","Leadership"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Workshops and leadership opportunities focused on computation, data, and real skill growth.",
    link: "https://live.stemfellowship.org/university-branches/university-of-calgary-branch/",
  },
  {
    id: "adss",
    title: "Actuarial & Data Science Society (ADSS)",
    type: "CPSC",
    tags: ["Data Science","Analytics","Python/R","Professional Development"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Data and analytics community with career development and practical learning events.",
    link: "https://adssucalgary.ca/",
  },
  {
    id: "sase",
    title: "Society of Asian Scientists & Engineers (SASE)",
    type: "CPSC",
    tags: ["Professional Development","Networking","Tech Career Skills"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Professional development and networking that helps you grow your career toolkit.",
    link: "https://www.saseucalgary.com/",
  },
  {
    id: "ucalgary_bioinformatics_club",
    title: "UCalgary Bioinformatics Club",
    type: "CPSC",
    tags: ["Bioinformatics","Python/R","Data Analysis","Research Skills"],
    effort: "1hr-3hr",
    deadline: "Year-Round",
    why: "Learn bioinformatics and research-style analysis while building a strong technical niche.",
    link: "https://linktr.ee/ucalgarybioinformatics",
  },
  {
    id: "igem_calgary",
    title: "iGEM Calgary (Dry Lab + Software)",
    type: "CPSC",
    tags: ["Modeling","Data Analysis","Software Tools","Teamwork"],
    effort: "2hr-8hr",
    deadline: "Summer + Year-Round",
    why: "Research-heavy team where you build modeling and software tools for synthetic biology projects.",
    link: "https://2025.igem.wiki/ucalgary/index.html",
  },
  {
    id: "hack4health",
    title: "Hack4Health UCalgary",
    type: "CPSC",
    tags: ["Hackathon Building","Teamwork","Rapid Prototyping"],
    effort: "8hr-24hr",
    deadline: "Event-Based",
    why: "High-energy hackathon community focused on building fast, learning, and shipping prototypes.",
    link: "https://www.hack4health.ca/",
  },
];
